spring:
    mvc:
      view:
        prefix: /WEB-INF/
        suffix: .jsp

    datasource:
            platform: postgres
            username: postgres
            password: 123
            url: jdbc:postgresql://localhost:5432/Bank
            driver-class-name: org.postgresql.Driver
    jpa:
            show-sql: true
            generate-ddl: true
