spring:
  profiles:
    active: prod
  application:
    name: SberBank
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


---
spring:
    profiles: test
    jpa:
          show-sql: true
          database: h2
          database-platform: H2
---
spring:
    profiles: prod
    datasource:
            platform: postgres
            username: postgres
            password: 123
            url: jdbc:postgresql://localhost:5432/Bank
            driver-class-name: org.postgresql.Driver
    jpa:
            show-sql: true
            generate-ddl: true

